addSbtPlugin("com.jsuereth" % "sbt-pgp" % "1.1.1")
addSbtPlugin("com.github.gseitz" % "sbt-release" % "1.0.9")
addSbtPlugin("org.xerial.sbt" % "sbt-sonatype" % "2.3")
addSbtPlugin("com.lucidchart"    % "sbt-scalafmt" % "1.15")
addSbtPlugin("org.scoverage" % "sbt-scoverage" % "1.5.1")