name: Continuous Integration

on:
  pull_request:
    branches: ['**']
  push:
    branches: ['**']

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    name: Build and Test
    strategy:
      fail-fast: false
      matrix:
        scala: [2.13.16, 3.3.6]
        clickhouse: [22.8, 23.3, 23.8] # 24.3 has issues because of join change https://clickhouse.com/docs/en/operations/analyzer#join-using-column-from-projection
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'sbt'
      - uses: sbt/setup-sbt@v1
      - name: Update '/etc/hosts' file
        run: ./.docker/update-hosts.sh

      - name: Generate SSL certificates
        run: ./.docker/generate-certs.sh

      - name: Docker Compose Action
        uses: hoverkraft-tech/compose-action@v2.0.1
        env:
          CLICKHOUSE_VERSION: ${{ matrix.clickhouse }}
        with:
          compose-file: './.docker/docker-compose.yml'
          down-flags: '--volumes'

      - name: Build project
        run: sbt ++${{ matrix.scala }} test IntegrationTest/test

      - name: Compress target directories
        run: tar cf targets.tar target client/target dsl/target testkit/target project/target

      - name: Upload target directories
        uses: actions/upload-artifact@v4
        with:
          name: target-${{ matrix.scala }}-${{matrix.clickhouse}}
          path: targets.tar

  publish:
    name: Publish Artifacts
    needs: [build]
    if: github.event_name != 'pull_request' && (github.ref == 'refs/heads/main')
    strategy:
      matrix:
        scala: [2.13.16, 3.3.6]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: 'sbt'
      - uses: sbt/setup-sbt@v1

      - name: Download target directories (${{ matrix.scala }})
        uses: actions/download-artifact@v4
        with:
          name: target-${{ matrix.scala }}

      - name: Inflate target directories (${{ matrix.scala }})
        run: |
          tar xf targets.tar
          rm targets.tar

      - name: Publish project
        run: sbt ++${{ matrix.scala }} +publish
