name: Continuous Integration

on:
  pull_request:
    branches: ['**']
  push:
    branches: ['**']

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    name: Build and Test
    strategy:
      fail-fast: false
      matrix:
        scala: [2.13.16, 3.3.1]
        clickhouse: [21.3, 21.8.14, 22.3]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - uses: sbt/setup-sbt@v1
      - name: Update '/etc/hosts' file
        run: ./.docker/update-hosts.sh

      - name: Generate SSL certificates
        run: ./.docker/generate-certs.sh

      - name: Docker Compose Action
        uses: hoverkraft-tech/compose-action@v2.0.1
        env:
          CLICKHOUSE_VERSION: ${{ matrix.clickhouse }}
        with:
          compose-file: './.docker/docker-compose.yml'
          down-flags: '--volumes'

      - uses: actions/cache@v4
        with:
          path: |
            ~/.sbt
            ~/.ivy2/cache
            ~/.coursier/cache/v1
            ~/.cache/coursier/v1
            ~/AppData/Local/Coursier/Cache/v1
            ~/Library/Caches/Coursier/v1
          key: sbt-cache-v2-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/build.properties') }}

#      - name: Check that workflows are up to date
#        run: sbt ++${{ matrix.scala }} githubWorkflowCheck

      - name: Build project
        run: sbt ++${{ matrix.scala }} test it:test

      - name: Compress target directories
        run: tar cf targets.tar target client/target dsl/target testkit/target project/target

      - name: Upload target directories
        uses: actions/upload-artifact@v4
        with:
          name: target-${{ matrix.scala }}-${{matrix.clickhouse}}
          path: targets.tar

  publish:
    name: Publish Artifacts
    needs: [build]
    if: github.event_name != 'pull_request' && (github.ref == 'refs/heads/main')
    strategy:
      matrix:
        scala: [2.13.16, 3.3.1]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - uses: sbt/setup-sbt@v1
      - uses: actions/cache@v4
        with:
          path: |
            ~/.sbt
            ~/.ivy2/cache
            ~/.coursier/cache/v1
            ~/.cache/coursier/v1
            ~/AppData/Local/Coursier/Cache/v1
            ~/Library/Caches/Coursier/v1
          key: sbt-cache-v2-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/build.properties') }}

      - name: Download target directories (3.3.1)
        uses: actions/download-artifact@v4
        with:
          name: target-3.3.1

      - name: Inflate target directories (3.3.1)
        run: |
          tar xf targets.tar
          rm targets.tar

      - name: Download target directories (2.13.16)
        uses: actions/download-artifact@v4
        with:
          name: target-2.13.16

      - name: Inflate target directories (2.13.16)
        run: |
          tar xf targets.tar
          rm targets.tar

      - name: Publish project
        run: sbt ++${{ matrix.scala }} +publish
