name: Release
on:
  push:
    branches: [main]
    tags: ["*"]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: sbt
      - uses: sbt/setup-sbt@v1
      - name: Update '/etc/hosts' file
        run: ./.docker/update-hosts.sh

      - name: Generate SSL certificates
        run: ./.docker/generate-certs.sh

      - name: Docker Compose Action
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: './.docker/docker-compose.yml'
          down-flags: '--volumes'
      - run: sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
